<?php

namespace Drupal\external_search_autocomplete\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

class ExternalSearchAutocompleteAdminForm extends ConfigFormBase {

  /**
   * @inheritDoc
   */
  protected function getEditableConfigNames() {
    return [
      'external_search_autocomplete.settings'
    ];
  }

  /**
   * @inheritDoc
   */
  public function getFormId() {
    return 'externalSearchAutocompleteAdminForm';
  }


  public function buildForm(array $form, FormStateInterface $form_state) {
    $config = $this->config('external_search_autocomplete.settings');

    $form['external_search_url'] = [
      '#type' => 'textfield',
      '#required' => TRUE,
      '#title' => $this->t('External Drupal server'),
      '#default_value' => $config->get('external_search_url')
    ];

    return parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub
  }


  public function submitForm(array &$form, FormStateInterface $form_state) {
    $config = $this->config('external_search_autocomplete.settings');
    $config->set('external_search_url', $form_state->getValue('external_search_url'));
    $config->save();
    parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
  }

}
